name: flutter_nfc_kit_example
description: Demonstrates how to use the flutter_nfc_kit plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit:
    path: ../
  logging: "^1.3.0"
  ndef: "^0.3.3"
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
