name: flutter_nfc_kit
description: Provide NFC functionality on Android, iOS & Web, including reading metadata, read & write NDEF records, and transceive layer 3 & 4 data with NFC tags / cards
version: 3.3.1
homepage: "https://github.com/nfcim/flutter_nfc_kit"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.0.1
  ndef: ^0.3.1
  convert: ^3.0.1
  logging: ^1.0.2
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.flutter_nfc_kit
        pluginClass: FlutterNfcKitPlugin
      ios:
        pluginClass: FlutterNfcKitPlugin
      web:
        pluginClass: FlutterNfcKitWeb
        fileName: flutter_nfc_kit_web.dart
