name: flutter_nfc_kit
description: Provide NFC functionality on Android, iOS & Web, including reading metadata, read & write NDEF records, and transceive layer 3 & 4 data with NFC tags / cards
version: 3.5.2
homepage: "https://github.com/nfcim/flutter_nfc_kit"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.8.1
  ndef: ^0.3.3
  convert: ^3.1.1
  logging: ^1.2.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.flutter_nfc_kit
        pluginClass: FlutterNfcKitPlugin
      ios:
        pluginClass: FlutterNfcKitPlugin
      web:
        pluginClass: FlutterNfcKitWeb
        fileName: flutter_nfc_kit_web.dart
