name: flutter_nfc_kit
description: Provide NFC functionality on Android and iOS, including reading metadata, read & write NDEF records, and transceive layer 3 & 4 data with NFC tags / cards
version: 2.2.1
homepage: "https://github.com/nfcim/flutter_nfc_kit"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  ndef: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.flutter_nfc_kit
        pluginClass: FlutterNfcKitPlugin
      ios:
        pluginClass: FlutterNfcKitPlugin
